Repository Spitgranger/SyncMaster, pull requests merged in 2025-03, with the labels that each got.

#466 docs(VnV Report): change functional requirement unit test coverage to failure
  docs/VnVReport/VnVReport.tex
Labels: documentation

#467 feat(docs): added functional requirement test results to VnVReport
  docs/VnVReport/VnVReport.tex
Labels: documentation

#471 feat(docs): added trace to modules for FRs
  docs/VnVReport/VnVReport.tex
Labels: documentation

#469 Update VnVReport.tex
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation

#408 Feat/rev0@implement document management module
  infrastructure/backend.yaml
  src/backend/service/database/db_table.py
  src/backend/service/document_management/__init__.py
  src/backend/service/document_management/document_management.py
  src/backend/service/file_storage/s3_bucket.py
  src/backend/service/handler.py
  src/backend/service/models/api/document.py
  src/backend/service/models/db/document.py
  src/backend/service/routes/protected/documents.py
  src/backend/service/routes/protected/site_visits.py
  src/backend/service/user_authentication/user_authentication.py
  src/backend/service/util.py
  test/backend/unit/constants.py
  test/backend/unit/document_management/__init__.py
  test/backend/unit/document_management/test_document_management.py
  test/backend/unit/file_storage/test_s3_bucket.py
  test/backend/unit/fixtures/api_gateway_event_v1.py
  test/backend/unit/fixtures/dynamodb.py
  test/backend/unit/fixtures/model/db/document.py
  test/backend/unit/routes/test_document_management.py
Labels: documentation

#481 feat(rev1): migrate user roles to use cognito user groups
  infrastructure/backend.yaml
  src/backend/service/handler.py
  src/backend/service/routes/protected/documents.py
  src/backend/service/routes/protected/site_visits.py
  src/backend/service/user_authentication/user_authentication.py
  src/backend/service/util.py
  test/backend/unit/fixtures/api_gateway_event_v1.py
  test/backend/unit/fixtures/cognito.py
  test/backend/unit/routes/test_site_visits.py
Labels: enhancement

#491 Feat/rev1@add expiry querying to documents
  infrastructure/backend.yaml
  src/backend/service/database/db_table.py
  src/backend/service/document_management/document_management.py
  src/backend/service/models/api/document.py
  src/backend/service/models/db/document.py
  src/backend/service/routes/protected/documents.py
  src/backend/service/util.py
  test/backend/unit/document_management/test_document_management.py
  test/backend/unit/fixtures/api_gateway_event_v1.py
  test/backend/unit/fixtures/dynamodb.py
  test/backend/unit/fixtures/model/db/document.py
  test/backend/unit/routes/test_document_management.py
Labels: enhancement

#499 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#528 Feat/rev1@add user requests
  infrastructure/backend.yaml
  src/backend/service/handler.py
  src/backend/service/models/api/user_requests.py
  src/backend/service/models/db/user_request.py
  src/backend/service/routes/protected/user_requests.py
  src/backend/service/routes/unprotected/auth.py
  src/backend/service/user_requests/__init__.py
  src/backend/service/user_requests/user_requests.py
  src/backend/service/util.py
  test/backend/unit/conftest.py
  test/backend/unit/constants.py
  test/backend/unit/fixtures/api_gateway_event_v1.py
  test/backend/unit/fixtures/cognito.py
  test/backend/unit/fixtures/dynamodb.py
  test/backend/unit/fixtures/model/db/user_request.py
  test/backend/unit/routes/test_user_requests.py
  test/backend/unit/user_requests/__init__.py
  test/backend/unit/user_requests/test_user_requests.py
Labels: enhancement

#533 fix: add content disposition parameter with filename
  src/backend/service/document_management/document_management.py
  src/backend/service/file_storage/s3_bucket.py
  src/backend/service/models/db/site_visit.py
  test/backend/unit/file_storage/test_s3_bucket.py
Labels: enhancement

#555 fix(rev1): change signin logic to reflect new requirements
  pyproject.toml
  src/backend/service/routes/protected/documents.py
  src/backend/service/routes/protected/users.py
  src/backend/service/routes/unprotected/auth.py
  src/backend/service/user_authentication/user_authentication.py
  src/backend/service/user_requests/user_requests.py
  test/backend/unit/fixtures/api_gateway_event_v1.py
  test/backend/unit/fixtures/cognito.py
  test/backend/unit/routes/test_user_requests.py
  test/backend/unit/routes/test_users.py
  test/backend/unit/user_authentication/test_user_authentication.py
  test/backend/unit/user_requests/test_user_requests.py
Labels: bug

#557 fix: infrastructure changes to allow admin cognito access
  infrastructure/backend.yaml
Labels: bug
